# Generated by Django 2.2.6 on 2019-10-19 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.IntegerField(choices=[(1, 'Incidents'), (2, 'Children'), (3, 'Activities'), (4, 'Comments')], default=1, max_length=1)),
                ('source_id', models.BigIntegerField()),
                ('title', models.CharField(max_length=255, null=True)),
                ('path', models.TextField()),
                ('features_encoding', models.TextField()),
                ('compare_till_id', models.BigIntegerField()),
                ('current_comparison_id', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comparison',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_distance', models.CharField(max_length=20, null=True)),
                ('sent_back', models.BooleanField(null=True)),
                ('reply_by_server', models.TextField(default='NULL', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('compared_image_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='compared_with', to='facesapp.Image')),
                ('image_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image', to='facesapp.Image')),
            ],
        ),
    ]
