# Generated by Django 2.2.6 on 2019-10-19 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facesapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='source',
            field=models.IntegerField(choices=[(1, 'Incidents'), (2, 'Children'), (3, 'Activities'), (4, 'Comments')], default=1),
        ),
    ]
