# Generated by Django 2.2.6 on 2019-10-19 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facesapp', '0002_auto_20191019_1740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comparison',
            old_name='compared_image_id',
            new_name='compared_image',
        ),
        migrations.RenameField(
            model_name='comparison',
            old_name='image_id',
            new_name='image',
        ),
    ]
