# Generated by Django 2.2.6 on 2019-10-19 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facesapp', '0003_auto_20191019_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='compare_till_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='image',
            name='current_comparison_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
