# Generated by Django 2.2.6 on 2019-10-21 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facesapp', '0007_auto_20191020_0925'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='image',
            name='features_encoding',
            field=models.BinaryField(null=True),
        ),
    ]
