# Generated by Django 2.2.6 on 2019-10-24 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facesapp', '0008_auto_20191021_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='attachment_id',
            field=models.BigIntegerField(default=111),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comparison',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='image', to='facesapp.Image'),
        ),
    ]
